version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cpf_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: cpf_api
    restart: always
    # environment:
    #   - DATABASE_URL=postgresql://user:password@db:5432/cpf_database
    # env_file:  # ✅ Load .env inside the container
    #   - .env
    depends_on:
      - db
    # environment:
    #   DATABASE_URL: postgresql://user:password@postgres_db:5432/cpf_database
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Only mounting the project, NOT `node_modules`
      - /app/node_modules # Prevents using local node_modules
    command: ["npm", "start"]

volumes:
  pgdata:
